### ISSUE TITLE
Server problem

### ISSUE THREAD

**Issue by Spirg** [rizalio/vpnpanel#1]
I installed your script but can not find where to add the server?

**Comment by rizalio** [comment]
Go to yourdomain.com/manage/admin and login there, default user is: admin@admin.admin password: admin

**Comment by Spirg** [comment]
http://i.imgur.com/jH0Lp9v.jpg is this bug?

**Comment by rizalio** [comment]
I don't think so, are you imported database correctly?, Or please attach the database screenshoot

**Comment by Spirg** [comment]
I used 
>  php artisan migrate

Inside the folder /var/www/vpnpanel
http://i.imgur.com/leExwud.jpg

**Comment by rizalio** [comment]
Run php artisan create to create new user

Pada tanggal 16 Agt 2017 5.01 PM, "Spirg" <notifications@github.com>
menulis:

**Comment by Spirg** [comment]
and its work, ty
